package Main;

import GUIAdmin.clienteBuscar;
import GUIAdmin.inventarioBuscar;
import GUIAdmin.pedidoBuscar;
import GUIAdmin.pedidoNuevo;
import GUIAdmin.ventasVentas;
import javax.swing.JTabbedPane;

/**
 *
 * @author aguare
 */
public class InicioAdmin extends javax.swing.JFrame {

    //Paneles 
    private ventasVentas venta = new ventasVentas();
    private pedidoNuevo pNuevo = new pedidoNuevo();
    private pedidoBuscar pBuscar = new pedidoBuscar();
    private inventarioBuscar iBuscar = new inventarioBuscar();
    private clienteBuscar cBuscar = new clienteBuscar();

    //Pestañas
    private JTabbedPane pedido = new JTabbedPane();

    /**
     * Creates new form InicioAdmin
     */
    public InicioAdmin() {
        initComponents();
        pestaPrincipal.add("Ventas", venta);
        pestaPrincipal.add("Pedido", pedido);
        pedido.add("Nuevo", pNuevo);
        pedido.add("Buscar", pBuscar);
        pestaPrincipal.add("Inventario", iBuscar);
        pestaPrincipal.add("Cliente", cBuscar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane5 = new javax.swing.JScrollPane();
        pestaPrincipal = new javax.swing.JTabbedPane();
        barraMenu = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        itemCambiarTienda = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        itemCerrarSesion = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuPedidos = new javax.swing.JMenu();
        itemPedidoEntrar = new javax.swing.JMenuItem();
        itemPedidoPendientes = new javax.swing.JMenuItem();
        itemPedidoAtrasados = new javax.swing.JMenuItem();
        itemPedidoTransito = new javax.swing.JMenuItem();
        menuSegunCliente = new javax.swing.JMenu();
        itemClienteCompras = new javax.swing.JMenuItem();
        itemClientePedidos = new javax.swing.JMenuItem();
        menuRTienda = new javax.swing.JMenu();
        itemRTiendaMasVendido = new javax.swing.JMenuItem();
        itemRTiendaNVendido = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemMasVendido = new javax.swing.JMenuItem();
        menuRegistros = new javax.swing.JMenu();
        itemEditarEmpleado = new javax.swing.JMenuItem();
        itemRegistrarEmpleado = new javax.swing.JMenuItem();
        menuTienda = new javax.swing.JMenu();
        itemEditarTienda = new javax.swing.JMenuItem();
        itemRegistrarTienda = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemTiempoTraslado = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jScrollPane4.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        setBackground(new java.awt.Color(66, 66, 66));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        barraMenu.setForeground(new java.awt.Color(0, 0, 0));
        barraMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        menuOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuOpciones.setForeground(new java.awt.Color(0, 0, 0));
        menuOpciones.setText("Opciones");
        menuOpciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuOpciones.setMargin(new java.awt.Insets(3, 3, 3, 3));

        itemCambiarTienda.setText("Cambiar de Tienda");
        itemCambiarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCambiarTiendaActionPerformed(evt);
            }
        });
        menuOpciones.add(itemCambiarTienda);

        jMenuItem3.setText("Cargar Datos");
        menuOpciones.add(jMenuItem3);

        itemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemCerrarSesion.setText("Cerrar Sesión");
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        menuOpciones.add(itemCerrarSesion);

        barraMenu.add(menuOpciones);

        menuReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuReportes.setForeground(new java.awt.Color(0, 0, 0));
        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuReportes.setMargin(new java.awt.Insets(3, 3, 3, 3));

        menuPedidos.setText("Pedidos");

        itemPedidoEntrar.setText("Por Entrar");
        itemPedidoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPedidoEntrarActionPerformed(evt);
            }
        });
        menuPedidos.add(itemPedidoEntrar);

        itemPedidoPendientes.setText("Pendientes");
        menuPedidos.add(itemPedidoPendientes);

        itemPedidoAtrasados.setText("Atrasados");
        itemPedidoAtrasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPedidoAtrasadosActionPerformed(evt);
            }
        });
        menuPedidos.add(itemPedidoAtrasados);

        itemPedidoTransito.setText("En Tránsito");
        menuPedidos.add(itemPedidoTransito);

        menuReportes.add(menuPedidos);

        menuSegunCliente.setText("Según Cliente");

        itemClienteCompras.setText("Compras");
        menuSegunCliente.add(itemClienteCompras);

        itemClientePedidos.setText("Pedidos");
        menuSegunCliente.add(itemClientePedidos);

        menuReportes.add(menuSegunCliente);

        menuRTienda.setText("Nivel Sucursal");

        itemRTiendaMasVendido.setText("Más vendido");
        menuRTienda.add(itemRTiendaMasVendido);

        itemRTiendaNVendido.setText("No vendido");
        menuRTienda.add(itemRTiendaNVendido);

        menuReportes.add(menuRTienda);

        jMenu1.setText("Nivel General");

        itemMasVendido.setText("Más vendido");
        jMenu1.add(itemMasVendido);

        menuReportes.add(jMenu1);

        barraMenu.add(menuReportes);

        menuRegistros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuRegistros.setForeground(new java.awt.Color(0, 0, 0));
        menuRegistros.setText("Empleados");
        menuRegistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuRegistros.setMargin(new java.awt.Insets(3, 3, 3, 3));

        itemEditarEmpleado.setText("Editar Empleado");
        menuRegistros.add(itemEditarEmpleado);

        itemRegistrarEmpleado.setText("Registrar Empleado");
        menuRegistros.add(itemRegistrarEmpleado);

        barraMenu.add(menuRegistros);

        menuTienda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuTienda.setForeground(new java.awt.Color(0, 0, 0));
        menuTienda.setText("Tienda");
        menuTienda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuTienda.setMargin(new java.awt.Insets(3, 3, 3, 3));

        itemEditarTienda.setText("Editar Tienda");
        menuTienda.add(itemEditarTienda);

        itemRegistrarTienda.setText("Registrar Tienda");
        menuTienda.add(itemRegistrarTienda);

        jMenuItem1.setText("Ver Tiendas");
        menuTienda.add(jMenuItem1);

        itemTiempoTraslado.setText("Tiempo Traslado");
        menuTienda.add(itemTiempoTraslado);

        barraMenu.add(menuTienda);

        menuAyuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuAyuda.setForeground(new java.awt.Color(0, 0, 0));
        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Acerca de");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAyuda.add(jMenuItem2);

        barraMenu.add(menuAyuda);

        jMenu2.setText("TIENDA SAN MARCOS 15/08/2020");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barraMenu.add(jMenu2);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itemCambiarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCambiarTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCambiarTiendaActionPerformed

    private void itemPedidoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPedidoEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPedidoEntrarActionPerformed

    private void itemPedidoAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPedidoAtrasadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPedidoAtrasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemCambiarTienda;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemClienteCompras;
    private javax.swing.JMenuItem itemClientePedidos;
    private javax.swing.JMenuItem itemEditarEmpleado;
    private javax.swing.JMenuItem itemEditarTienda;
    private javax.swing.JMenuItem itemMasVendido;
    private javax.swing.JMenuItem itemPedidoAtrasados;
    private javax.swing.JMenuItem itemPedidoEntrar;
    private javax.swing.JMenuItem itemPedidoPendientes;
    private javax.swing.JMenuItem itemPedidoTransito;
    private javax.swing.JMenuItem itemRTiendaMasVendido;
    private javax.swing.JMenuItem itemRTiendaNVendido;
    private javax.swing.JMenuItem itemRegistrarEmpleado;
    private javax.swing.JMenuItem itemRegistrarTienda;
    private javax.swing.JMenuItem itemTiempoTraslado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuPedidos;
    private javax.swing.JMenu menuRTienda;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSegunCliente;
    private javax.swing.JMenu menuTienda;
    private javax.swing.JTabbedPane pestaPrincipal;
    // End of variables declaration//GEN-END:variables
}
