package GUIAdmin;

import BInstancias.Producto;
import BInstancias.Tienda;
import BManejadores.ConsultasOtros;
import BManejadores.ConsultasProducto;
import GUIConsultas.PanelProducto;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author aguare
 */
public class inventarioBuscar extends javax.swing.JPanel {

    private Tienda tienda;

    private ArrayList<Tienda> listaTiendas;
    private ArrayList<Producto> busquedaProductos;
    private ArrayList<PanelProducto> paneles;

    private ConsultasOtros otros = new ConsultasOtros();
    private ConsultasProducto cPro = new ConsultasProducto();

    /**
     * Creates new form inventarioBuscar
     */
    public inventarioBuscar(Tienda tienda) {
        initComponents();
        this.tienda = tienda;
        listaTiendas = otros.ObtenerTiendas();
        ingresarTiendas();
    }

    private void ingresarTiendas() {
        for (Tienda listaTienda : listaTiendas) {
            comboTiendas.addItem("" + listaTienda.getCodTienda() + ",\t" + listaTienda.getNombre());
        }
        comboTiendas.addItem("Todas");
        comboTiendas.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        comboTipoB = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        textEntrada = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        comboTiendas = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        comboOrden = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelBuscarInventario = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel25.setText("BUSCAR POR:");

        comboTipoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CÓDIGO", "NOMBRE" }));
        comboTipoB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoBItemStateChanged(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel27.setText("INGRESE:");

        textEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEntradaKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel26.setText("TIENDA:");

        comboTiendas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTiendasItemStateChanged(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel28.setText("ORDEN:");

        comboOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASCENDENTE", "DESCENDENTE" }));
        comboOrden.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboOrdenItemStateChanged(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("CODIGO");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("NOMBRE");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("FABRICANTE");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("CANTIDAD");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("PRECIO");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("OPCIONES");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelBuscarInventario.setPreferredSize(new java.awt.Dimension(925, 519));

        javax.swing.GroupLayout panelBuscarInventarioLayout = new javax.swing.GroupLayout(panelBuscarInventario);
        panelBuscarInventario.setLayout(panelBuscarInventarioLayout);
        panelBuscarInventarioLayout.setHorizontalGroup(
            panelBuscarInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        panelBuscarInventarioLayout.setVerticalGroup(
            panelBuscarInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelBuscarInventario);

        jButton1.setText("INGRESAR PRODUCTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NUEVO FABRICANTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboTipoB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textEntrada)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTiendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboOrden, 0, 250, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jButton1)
                            .addComponent(comboTiendas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(comboOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(comboTipoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(textEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistrarProducto registrar = new RegistrarProducto(tienda);
        registrar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEntradaKeyTyped
        realizarBusqueda(textEntrada.getText());
    }//GEN-LAST:event_textEntradaKeyTyped

    private void realizarBusqueda(String entrada) {
        int tipo = comboTipoB.getSelectedIndex();
        int tienda = comboTiendas.getSelectedIndex();
        int tam = listaTiendas.size();
        String t = listaTiendas.get(tienda).getCodTienda();
        if (tipo == 0 && tienda > tam) {
            busquedaProductos = cPro.ObtenerProductosCodigo(entrada);
            llenarScrollPanel();
        } else if (tipo == 0 && tienda < tam) {
            busquedaProductos = cPro.ObtenerProductosCodigoTienda(entrada, t);
            llenarScrollPanel();
        } else if (tipo == 1 && tienda > tam) {
            busquedaProductos = cPro.ObtenerProductosNombre(entrada);
            llenarScrollPanel();
        } else if (tipo == 1 && tienda < tam) {
            busquedaProductos = cPro.ObtenerProductosCodigoTienda(entrada, t);
            llenarScrollPanel();
        }
    }
    private void comboOrdenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboOrdenItemStateChanged
        insertarPaneles(comboOrden.getSelectedIndex());
    }//GEN-LAST:event_comboOrdenItemStateChanged

    private void comboTipoBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoBItemStateChanged
        realizarBusqueda(textEntrada.getText());
    }//GEN-LAST:event_comboTipoBItemStateChanged

    private void comboTiendasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTiendasItemStateChanged

    }//GEN-LAST:event_comboTiendasItemStateChanged

    private void llenarScrollPanel() {
        if (paneles != null) {
            quitarPaneles();
        }
        paneles = new ArrayList();
        System.gc();
        int tam = busquedaProductos.size();
        for (int i = 0; i < tam; i++) {
            paneles.add(i, new PanelProducto(busquedaProductos.get(i)));
            paneles.get(i).setBounds((0), ((i * 53)), 932, 52);
        }
        insertarPaneles(comboOrden.getSelectedIndex());
    }

    private void insertarPaneles(int opcion) {
        if (opcion == 0) {
            for (PanelProducto panele : paneles) {
                panelBuscarInventario.add(panele);
                panele.setVisible(true);
            }
            panelBuscarInventario.repaint();
        } else {
            for (int i = paneles.size() - 1; i >= 0; i--) {
                panelBuscarInventario.add(paneles.get(i));
                paneles.get(i).setVisible(true);
            }
            panelBuscarInventario.repaint();
        }
        panelBuscarInventario.setPreferredSize(new Dimension(932, 53 * paneles.size()));
    }

    private void quitarPaneles() {
        for (PanelProducto panele : paneles) {
            panele.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboOrden;
    private javax.swing.JComboBox<String> comboTiendas;
    private javax.swing.JComboBox<String> comboTipoB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBuscarInventario;
    private javax.swing.JTextField textEntrada;
    // End of variables declaration//GEN-END:variables
}
