package GUIConsultas;

import BInstancias.Producto;
import BInstancias.Tienda;
import BManejadores.ConsultasProducto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aguare
 */
public class EditarProducto extends javax.swing.JDialog {
    
    private Producto producto;
    ConsultasProducto consultas = new ConsultasProducto();
    ArrayList<Tienda> tiendas;

    /**
     * Creates new form EditarProducto
     *
     * @param parent
     */
    public EditarProducto(java.awt.Frame parent, boolean modal, Producto producto) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.producto = producto;        
        actualizarInfo();
    }
    
    private void actualizarInfo() {
        textCodigo.setText(producto.getIdProducto());
        textNombre.setText(producto.getNombre());
        textPrecio.setText("" + producto.getPrecio());
        spinnerCantidad.setValue(producto.getCantidad());
        spinnerMeses.setValue(producto.getGarantiaMeses());
        textDescripcion.setText(producto.getDescripcion());
        tiendas = consultas.tiendaExistencia(producto.getIdProducto());
        for (Tienda tienda : tiendas) {
            comboTiendas.addItem(tienda.getCodTienda() + ", " + tienda.getNombre());
        }
        comboTiendas.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        spinnerCantidad = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        spinnerMeses = new javax.swing.JSpinner();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        buttonCambios = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        comboTiendas = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 290));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setText("CÓDIGO:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 420, 19);

        textCodigo.setEditable(false);
        getContentPane().add(textCodigo);
        textCodigo.setBounds(6, 26, 420, 26);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel36.setText("NOMBRE:");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(6, 70, 420, 19);
        getContentPane().add(textNombre);
        textNombre.setBounds(6, 95, 420, 26);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel39.setText("PRECIO:");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(6, 139, 175, 19);
        getContentPane().add(textPrecio);
        textPrecio.setBounds(6, 164, 184, 26);

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel38.setText("TIENDA UBICACIÓN:");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(470, 140, 180, 19);

        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(spinnerCantidad);
        spinnerCantidad.setBounds(660, 160, 174, 26);

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel40.setText("MESES DE GARANTÍA:");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(220, 130, 190, 19);

        spinnerMeses.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinnerMeses);
        spinnerMeses.setBounds(220, 160, 190, 26);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel37.setText("DESCRIPCIÓN:");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(464, 6, 223, 19);

        textDescripcion.setColumns(20);
        textDescripcion.setRows(5);
        jScrollPane1.setViewportView(textDescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(464, 26, 377, 100);

        buttonCambios.setText("CONFIRMAR CAMBIOS");
        buttonCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCambios);
        buttonCambios.setBounds(650, 220, 190, 31);

        buttonCancelar.setText("CANCELAR");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancelar);
        buttonCancelar.setBounds(10, 220, 160, 31);

        comboTiendas.setFocusCycleRoot(true);
        comboTiendas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTiendasItemStateChanged(evt);
            }
        });
        getContentPane().add(comboTiendas);
        comboTiendas.setBounds(470, 160, 170, 25);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel41.setText("CANTIDAD:");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(660, 140, 174, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiosActionPerformed
        boolean si = consultas.actualizarProducto(textNombre.getText(), textPrecio.getText(), textDescripcion.getText(),
                "" + spinnerMeses.getValue(), producto.getIdProducto(), tiendas.get(comboTiendas.getSelectedIndex()), (int) spinnerCantidad.getValue());
        if (si) {
            JOptionPane.showMessageDialog(null, "Producto Actualizado", "Actualización", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No se puedo Actualizar, verifique las modificaciones", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCambiosActionPerformed

    private void comboTiendasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTiendasItemStateChanged
        comboTiendas.setEnabled(false);
        spinnerCantidad.setValue(consultas.cantidadEnTienda(producto.getIdProducto(), tiendas.get(comboTiendas.getSelectedIndex()).getCodTienda()));
    }//GEN-LAST:event_comboTiendasItemStateChanged

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCambios;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JComboBox<String> comboTiendas;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JSpinner spinnerMeses;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables

}
